### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by CubedWorldNET** [ahaggard2013/Reddit-Account-Generator-and-Mass-Upvoter#1]
Hey, not sure what I have done wrong but I followed all the steps and receive this error:
`[+] creating account for R8AD19NP0RXXV1Q with password PJWHPJ7S89ILY4C
Traceback (most recent call last):
  File "creator.py", line 79, in <module>
    main()
  File "creator.py", line 59, in main
    account_created = create_account(username, password)
  File "creator.py", line 21, in create_account
    browser = webdriver.Firefox(firefox_profile=profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 142, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
`

**Comment by ahaggard2013** [comment]
seems like something to do with permissions, I'd try running it as super user if you haven't.  Does selenium work at all?  Try running this in another file.
```
from selenium import webdriver
browser = webdriver.Firefox()
browser.get('http://google.com')
```
Will likely find more info in the log file generated too.

**Comment by CubedWorldNET** [comment]
Hey,

Appears you are right about Selenium not working at all. 

> Traceback (most recent call last):
  File "test.py", line 2, in <module>
    browser = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 142, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error


Also the geckodriver.log file is actually empty, thanks for providing help :)

**Comment by ahaggard2013** [comment]
Did you try running it with sudo?

**Comment by CubedWorldNET** [comment]
Hey, yes I did

**Comment by Mihaitafox11** [comment]
I got the same error and I'm on windows. Help :(
