### ISSUE TITLE
Creation issue

### ISSUE THREAD

**Issue by Clintoxen** [ahaggard2013/Reddit-Account-Generator-and-Mass-Upvoter#4]
```
D:\Downloads\Reddit-Account-Generator-and-Mass-Upvoter-master\Reddit-Account-Generator-and-Mass-Upvoter-master>python creator.py
'clear' is not recognized as an internal or external command,
operable program or batch file.
[+] creating account for 8TAK31BCS5XAQV6 with password S8ZMHS53FC9JA0R
Traceback (most recent call last):
  File "creator.py", line 79, in <module>
    main()
  File "creator.py", line 59, in main
    account_created = create_account(username, password)
  File "creator.py", line 38, in create_account
    input = raw_input("[*] Solve captcha, create account, then press enter... enter 'r' as input if captcha doesn't appear to skip username" + '\n')
NameError: name 'raw_input' is not defined
``` 

it worked up until the time it needed to write that data into the file

**Comment by Clintoxen** [comment]
Hmm i think i figured it out, in py3 raw_input() is just simply input(). Not sure if this was supposed to be based on 2.7 or not @ahaggard2013

**Comment by Clintoxen** [comment]
OK I ended up doing something else to get tor to restart. Doesnt seem to be skipping the names that didnt have a captcha but i will try to figure that out tomorrow
